---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalcf/cred-alert-ci

inputs:
- name: cred-alert
  path: go/src/github.com/pivotal-cf/cred-alert
- name: dep

outputs:
- name: updated-repo

run:
  path: go/src/github.com/pivotal-cf/cred-alert/ci/scripts/update-dependencies
